webtalk_init -webtalk_dir C:/Users/horku/Documents/School/EECE/COEN 4710/computer_hardware_projects/Project 2/Memory Unit/Memory Unit.sim/sim_1/behav/xsim/xsim.dir/memUnit_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 23 11:22:59 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ab98bcaf-206e-4c0b-825b-ba5cf201a27d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f24f3245fea94cb297dd17eb7bb87797" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5484_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3928178604 -regid "" -xml C:/Users/horku/Documents/School/EECE/COEN 4710/computer_hardware_projects/Project 2/Memory Unit/Memory Unit.sim/sim_1/behav/xsim/xsim.dir/memUnit_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/horku/Documents/School/EECE/COEN 4710/computer_hardware_projects/Project 2/Memory Unit/Memory Unit.sim/sim_1/behav/xsim/xsim.dir/memUnit_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/horku/Documents/School/EECE/COEN 4710/computer_hardware_projects/Project 2/Memory Unit/Memory Unit.sim/sim_1/behav/xsim/xsim.dir/memUnit_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
